# Generated by Django 5.1.7 on 2025-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, default=84, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
