# Generated by Django 5.1.7 on 2025-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_marketuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=3),
            preserve_default=False,
        ),
    ]
