# Generated by Django 5.1.7 on 2025-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_offer_min_delivery_time_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, default=54, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'in_progress'), ('completed', 'completed')], default='inprogress', max_length=30),
        ),
    ]
