# Generated by Django 5.1.7 on 2025-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_marketuser_type_alter_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='working_hours',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, default=69, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
    ]
