# Generated by Django 5.1.7 on 2025-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketuser',
            name='description',
            field=models.CharField(default='description', max_length=150),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='email',
            field=models.EmailField(default='no@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='file',
            field=models.FileField(default='', upload_to='profile-images/'),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='last_name',
            field=models.CharField(default='Last name', max_length=30),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='location',
            field=models.CharField(default='Bozen', max_length=30),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='tel',
            field=models.CharField(default='123456789', max_length=30),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='working_hours',
            field=models.CharField(default='9 to 17', max_length=15),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
