# Generated by Django 5.1.7 on 2025-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketuser_created_at_marketuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='file',
            field=models.FileField(upload_to='profile-images/'),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='tel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='working_hours',
            field=models.CharField(max_length=15),
        ),
    ]
