# Generated by Django 5.1.7 on 2025-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_marketuser_description_alter_marketuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=20),
        ),
    ]
