# Generated by Django 5.1.7 on 2025-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_marketuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile-images/'),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('business', 'business')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='working_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
