# Generated by Django 5.1.7 on 2025-03-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_marketuser_description_alter_marketuser_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketuser',
            name='email',
        ),
    ]
