# Generated by Django 5.1.7 on 2025-03-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_marketuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], default='customer', max_length=20),
            preserve_default=False,
        ),
    ]
