# Generated by Django 5.1.7 on 2025-04-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketuser', verbose_name='Market User'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business', to='market.marketuser')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='market.marketuser')),
                ('offerdetail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_detail', to='market.offerdetail')),
            ],
        ),
    ]
