# Generated by Django 5.1.7 on 2025-05-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_offer_updated_at_alter_offer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_business', to='market.marketuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_customer', to='market.marketuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offerdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='market.offerdetail'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_business_user', to='market.marketuser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer', to='market.marketuser')),
            ],
        ),
    ]
